name: CI/CD

on:
  push:
    branches: ['main']

jobs:
  install-dep:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout the code repo
        uses: actions/checkout@v3
      
      - name: Initializing the project with node.js
        uses: actions/setup-node@v3
        with:
          version: ${{matrix.node-version}}
      
      - name: Install dependencies 
        run: npm ci
  build-and-push:
    runs-on: ubuntu-latest
    needs: ['install-dep']
    steps:
      - name: Checkout the code repo
        uses: actions/checkout@v3
      
      - name: Set up docker
        uses: docker/setup-buildx-action@v2

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the image to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKER_USER }}/node-chat-app:${{ github.sha }}
  update-manifest:
    runs-on: ubuntu-latest
    needs: ['build-and-push']
    steps:
      - name: Checkout to manifest repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.G_NAME }}/kubernetesmanifest
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}
      - name: Setup git config and update repo
        run: |
          git config --global user.email ${{ secrets.G_EMAIL }}
          git config --global user.name ${{ secrets.G_NAME }}
          sed -i "s#${{ secrets.DOCKER_USER }}.*#${{ secrets.DOCKER_USER }}/node-chat-app:${{ github.sha }}#g" deployment.yaml
          git add -A
          git commit -m "Update image for ${{ github.sha }}"
          git push origin main